name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, 3.12]
        toxenv: [django42, quality]

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: make requirements

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

  frontend-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: install dependencies
        working-directory: ./frontend
        run: npm install

      - name: typecheck
        working-directory: ./frontend
        run: npm run typecheck

      - name: build
        working-directory: ./frontend
        run: npm run build

      - name: test
        working-directory: ./frontend
        run: npm run test
